apiVersion: v1
kind: Secret
metadata:
  name: aliyun-registry-key
  namespace: article-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiY3JwaS1xYXhsaXN1d2o5ZnA1Z3Y5LmNuLWJlaWppbmcucGVyc29uYWwuY3IuYWxpeXVuY3MuY29tIjogeyJ1c2VybmFtZSI6ICJuaWNrMTE5MTQ3Mjc3NCIsICJwYXNzd29yZCI6ICJmZHMwMDkxMyJ9fX0=
  # 使用`echo -n '{"auths": {"crpi-qaxlisuwj9fp5gv9.cn-beijing.personal.cr.aliyuncs.com": {"username": "nick1191472774", "password": "YOUR_PASSWORD"}}}' | base64`生成
   # echo -n '{"auths": {"crpi-qaxlisuwj9fp5gv9.cn-beijing.personal.cr.aliyuncs.com": {"username": "nick1191472774", "password": "fds00913"}}}' | base64 -w 0
