apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: article-system
type: Opaque
stringData:
  mysql-root-password: "${MYSQL_ROOT_PASSWORD}"
  mysql-replication-password: "${MYSQL_ROOT_PASSWORD}"
  redis-password: "redis123"
